# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Event" do
    optional :name, :string, 1
    optional :date, :string, 2
  end
  add_message "EventAdded" do
    optional :added, :bool, 1
  end
end

Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("Event").msgclass
EventAdded = Google::Protobuf::DescriptorPool.generated_pool.lookup("EventAdded").msgclass
