# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: calendar.proto for package ''

require 'grpc'
require 'calendar_pb'

module Calendar
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Calendar'

    rpc :AddEvent, Event, EventAdded
    rpc :ShowEvents, EventRange, stream(Event)
  end

  Stub = Service.rpc_stub_class
end
